baseURL = ""
languageCode = "en-us"
title = "neapowers"
theme = "github-style"
googleAnalytics = "G-Z53ZY4HCTD"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Matthew Powers"
  description = "Spark nerd, reggateon lover"
  twitter = "neapowers"
  github = "MrPowers"
  location = "Medellín"
  url = "https://neapowers.com"
